apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-krfh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-krfh
    app.kubernetes.io/part-of: ci10t-776-0094-app
  name: devfile-sample-krfh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-krfh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-krfh
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0094-tenant/ci10t-776-0094-app/devfile-sample-krfh@sha256:56128b4a41fc4b1316eb3cfde70bee7fb7fdaec91af170cc010abd8acf1bfc38
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
